### ISSUE TITLE
download button related pages designs

### ISSUE THREAD

**Issue by tranquille3000** [anthonyjoeseph/Broccoli#119]
![broccoli after read page-01](https://user-images.githubusercontent.com/31079316/33149283-32bd909c-cf9d-11e7-98b4-08db97bc2c53.jpg)

![broccoli app main with downloaded 4qqaa-01](https://user-images.githubusercontent.com/31079316/33149308-4c563a0e-cf9d-11e7-924d-5b38c9bb8fa6.jpg)

![broccoli app category page 4qqq-01](https://user-images.githubusercontent.com/31079316/33149343-6a33b1a0-cf9d-11e7-8894-bfa219e2691d.jpg)
![cover page design 1qq-01](https://user-images.githubusercontent.com/31079316/33149372-7fc615f8-cf9d-11e7-895e-9ddc54cd4b57.jpg)

button can be found under various download button folder in google doc

**Comment by anthonyjoeseph** [comment]
In the last image, the cover page, does the star icon appear when the book is downloaded, or when it isn't?
