### ISSUE TITLE
no wifi design bug

### ISSUE THREAD

**Issue by tranquille3000** [anthonyjoeseph/Broccoli#132]
![kakaotalk_20171218_201622216](https://user-images.githubusercontent.com/31079316/34135795-c23f60d6-e430-11e7-9241-662d4b9fc11e.jpg)

When I launch it without the internet connection, it looks like above

**Comment by anthonyjoeseph** [comment]
what's wrong with it?

**Comment by anthonyjoeseph** [comment]
The goblin thumbnail didn't load?

**Comment by anthonyjoeseph** [comment]
can you try deleting the book and downloading it again?

**Comment by anthonyjoeseph** [comment]
the bookpicker should be pushed to the left
