### ISSUE TITLE
Referral webpage design

### ISSUE THREAD

**Issue by tranquille3000** [anthonyjoeseph/Broccoli#139]
![referral webpage design 1a-01](https://user-images.githubusercontent.com/31079316/34507186-bac51954-f001-11e7-8af9-21a7df70499d.jpg)

![referral webpage design ipad mini 1a-01](https://user-images.githubusercontent.com/31079316/34540376-4e2d058a-f0a2-11e7-83e8-11e3d31e82ef.jpg)
![referral webpage design desktop 1a-01](https://user-images.githubusercontent.com/31079316/34540384-50ef8acc-f0a2-11e7-94a5-280549d45fc7.jpg)

The pictures are mobile -> ipad -> desktop order
The graphic in the middle is the character user chooses.

**Comment by anthonyjoeseph** [comment]
copy to clipboard: https://facebook.github.io/react-native/docs/clipboard.html

**Comment by anthonyjoeseph** [comment]
obsolete
