### ISSUE TITLE
membership purchase page

### ISSUE THREAD

**Issue by tranquille3000** [anthonyjoeseph/Broccoli#143]
![broccoli app sign up membership page2 2qqaa-01](https://user-images.githubusercontent.com/31079316/34687278-3528ff3e-f47c-11e7-8701-ddea1efc4fdb.jpg)

membership purchase page will appear when user tries to open locked titles, after signing up, from menu.

**Comment by anthonyjoeseph** [comment]
Idea - should one of these options be to refer another user?
