### ISSUE TITLE
language button - english language

### ISSUE THREAD

**Issue by tranquille3000** [anthonyjoeseph/Broccoli#26]
English should be US flag instead of UK

**Comment by anthonyjoeseph** [comment]
when should the uk flag be used?

**Comment by anthonyjoeseph** [comment]
* shouldn't be used until further notice

**Comment by anthonyjoeseph** [comment]
fixed in upcoming build 1.10 -https://github.com/anthonyjoeseph/Broccoli/commit/0df2df503b80516dae184e2b4e0e13303c0a9dec
