### ISSUE TITLE
Text box default setting

### ISSUE THREAD

**Issue by tranquille3000** [anthonyjoeseph/Broccoli#28]
![kakaotalk_20170829_212332042](https://user-images.githubusercontent.com/31079316/29851118-613a05c0-8d00-11e7-9b13-16c92d6e50e3.jpg)

Whenever we slide to next page, the text box will come up as a default. We need to change it so that if the user have the text box down, it stays down even if you slide to next page.

**Comment by anthonyjoeseph** [comment]
Has been fixed since build 1.9 I believe. Thanks for making a separate issue!
