### ISSUE TITLE
iPad in book buttons and textbox

### ISSUE THREAD

**Issue by tranquille3000** [anthonyjoeseph/Broccoli#29]
The buttons and textbox in iPad look too small. Also the scroll bar is too short and small. I couldn't send the screenshot to my computer. You can just turn on the iPad and see them in the gallery. I am charging it right now.

**Comment by anthonyjoeseph** [comment]
How big should they be on an ipad? And do you mean the scroll bar should be longer aka lengthwise  <--------> ? Percentages of the current size would be good, or a hand drawing

**Comment by anthonyjoeseph** [comment]
fixed in upcoming build 1.6
