### ISSUE TITLE
Cover page (what should be kept and what should disappear)

### ISSUE THREAD

**Issue by tranquille3000** [anthonyjoeseph/Broccoli#38]
For every cover page, we just want the go back button(as shown in black circle in the picture)Weddd

We do not want any other buttons.

![kakaotalk_20170908_150114539](https://user-images.githubusercontent.com/31079316/30227183-b730a260-94a6-11e7-93fb-89111c95d27c.jpg)

**Comment by anthonyjoeseph** [comment]
fixed in upcoming build 1.14 - https://github.com/anthonyjoeseph/Broccoli/commit/6985babc60965a6057ab48931a3258072cdb05ef
