### ISSUE TITLE
Random pick function

### ISSUE THREAD

**Issue by tranquille3000** [anthonyjoeseph/Broccoli#43]
![broccoli app main 1qq-01](https://user-images.githubusercontent.com/31079316/30234199-052ba5d8-94c9-11e7-81e3-995101331669.jpg)

The question mark thumbnail in the picture stands for the random pick function. When kids touch the random thumbnail, it picks a random book for them.

**Comment by anthonyjoeseph** [comment]
*picks a random book in the category that's currently chosen
