### ISSUE TITLE
In book, text board design change

### ISSUE THREAD

**Issue by tranquille3000** [anthonyjoeseph/Broccoli#44]
![zzzzzzzzzzzaaaaaaaaa-01](https://user-images.githubusercontent.com/31079316/30252233-4780b710-963c-11e7-936b-dea2498720d3.jpg)

We need to make the text board transparent so that it will improve the reading experience. We also need to have different size for text boards depending on which device you are using. The text inside will have black outline to make it more clear.

Also I think we should get rid of the sliding bar for now.

**Comment by anthonyjoeseph** [comment]
https://github.com/anthonyjoeseph/Broccoli/commit/24600255d01febeac572eb7d6e1846c6ddf7c5d6
