### ISSUE TITLE
In book design

### ISSUE THREAD

**Issue by tranquille3000** [anthonyjoeseph/Broccoli#49]
![kakaotalk_20170918_182940109](https://user-images.githubusercontent.com/31079316/30567650-6850d1f0-9c9f-11e7-94ff-f526b71d40f8.jpg)

The above is capture from the recent version of our app. 
It should look like this. The textboard location and size is wrong. Text size should be bigger (buttons should be different is well due to design change that we talked about on the other day.)

![ggggvv-01](https://user-images.githubusercontent.com/31079316/30567670-7570536a-9c9f-11e7-8823-726d9019346d.jpg)

**Comment by anthonyjoeseph** [comment]
fixed with https://github.com/anthonyjoeseph/Broccoli/commit/6187a51606520e11cd295924665d3da96570ec43
