### ISSUE TITLE
Korean Language Error

### ISSUE THREAD

**Issue by tranquille3000** [anthonyjoeseph/Broccoli#51]
![kakaotalk_20170926_191948123](https://user-images.githubusercontent.com/31079316/30888817-91f51262-a2f0-11e7-8b63-32abb2b2de7b.jpg)

Korean language appears like above.

**Comment by anthonyjoeseph** [comment]
@tranquille3000 What device was this on? And which book?

**Comment by anthonyjoeseph** [comment]
iPhone

**Comment by anthonyjoeseph** [comment]
caused by https://github.com/anthonyjoeseph/readBroccoliSite/issues/19
