### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by tranquille3000** [anthonyjoeseph/Broccoli#68]
![kakaotalk_20171016_083811877](https://user-images.githubusercontent.com/31079316/31614340-1115d2ee-b254-11e7-9475-59275816c6ea.jpg)

Sometimes this shows up in ios when I first load the app

**Comment by anthonyjoeseph** [comment]
Only appears when the app has been open for several hours

**Comment by anthonyjoeseph** [comment]
@tranquille3000 this has possibly been fixed; please let me know if you get the error again. It's difficult to test since the app has to be closed for several hours for the bug to appear. If it doesn't happen for a week, I'll close the issue.

**Comment by anthonyjoeseph** [comment]
(just for Anthony) current solution uses https://github.com/aws/amazon-cognito-identity-js and https://github.com/CodingZeal/react-native-appstate-listener

**Comment by anthonyjoeseph** [comment]
https://github.com/anthonyjoeseph/Broccoli/issues/100

**Comment by anthonyjoeseph** [comment]
This is what's expiring:

http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html

**Comment by anthonyjoeseph** [comment]
Use case 4:
https://github.com/aws/amazon-cognito-identity-js

react-native wrapper:
https://github.com/AirLabsTeam/react-native-aws-cognito-js

react-native cognito sync:
AirLabsTeam/react-native-aws-cognito-js#2

**Comment by anthonyjoeseph** [comment]
possibly helpful?
https://aws.amazon.com/blogs/mobile/understanding-amazon-cognito-authentication/

**Comment by anthonyjoeseph** [comment]
api reference:
http://docs.aws.amazon.com/cognitosync/latest/APIReference/Welcome.html

**Comment by anthonyjoeseph** [comment]
![kakaotalk_20171101_155331605](https://user-images.githubusercontent.com/3209763/32294651-2693468a-bf1d-11e7-8e83-1ae6654e426e.jpg)
