### ISSUE TITLE
Features of the 1st IOS launch version

### ISSUE THREAD

**Issue by tranquille3000** [anthonyjoeseph/Broccoli#73]
We will initially launch IOS first and then work on Android.

1. Referral
2. Apple subscription
3. Interactive sound effect 
4. Interactive animation
5. Interactive definition explaining animation
6. Interactive colour unlock 
7. Background music
8. Multiple languages (Spanish, Chinese, Korean, English, French, Japanese)
9. Animation without touching
10. Read to you(Story reading function when you hit play button)
11. Counting the number of times each user uses the Interactive features(Animation, Sound, Colour, Definition, Language change, Read to me -> all the Interactive features)

**Comment by anthonyjoeseph** [comment]
https://github.com/anthonyjoeseph/Broccoli/issues/78
https://github.com/anthonyjoeseph/Broccoli/issues/79
https://github.com/anthonyjoeseph/Broccoli/issues/80
https://github.com/anthonyjoeseph/Broccoli/issues/81
https://github.com/anthonyjoeseph/Broccoli/issues/82
https://github.com/anthonyjoeseph/Broccoli/issues/83
https://github.com/anthonyjoeseph/Broccoli/issues/84
https://github.com/anthonyjoeseph/Broccoli/issues/85
https://github.com/anthonyjoeseph/Broccoli/issues/86
https://github.com/anthonyjoeseph/Broccoli/issues/87
https://github.com/anthonyjoeseph/Broccoli/issues/88
