### ISSUE TITLE
little frog error

### ISSUE THREAD

**Issue by tranquille3000** [anthonyjoeseph/Broccoli#76]
![kakaotalk_20171018_205837701](https://user-images.githubusercontent.com/31079316/31751058-8a6b6e0c-b451-11e7-91d4-cbaf9d7cfc47.jpg)

Little frog book got stuck in this screen.

**Comment by anthonyjoeseph** [comment]
If you wait this screen will go away. This screen tells you that the background music is loading. Once this screen goes away, the music loads very quickly.
