### ISSUE TITLE
Design change for the title selecting page

### ISSUE THREAD

**Issue by tranquille3000** [anthonyjoeseph/Broccoli#77]
![broccoli app main 3qqaac-01](https://user-images.githubusercontent.com/31079316/32005563-9b41d84e-b972-11e7-96a0-bd05958c032c.jpg)

We will change the design of the title selecting(main page) page like the above picture.

**Comment by anthonyjoeseph** [comment]
The question mark button always shows "The Abandoned Princess"?

**Comment by anthonyjoeseph** [comment]
And how should it look on tablets? The same thing but bigger?

**Comment by anthonyjoeseph** [comment]
The text for the Question Mark should be "Pick a random book"

**Comment by tranquille3000** [comment]
Two rows of thumbnails for tablets

**Comment by tranquille3000** [comment]
The colours of the thumbnails are going to be selected randomly, but do not repeat the colour unless all the other colours are used.

**Comment by tranquille3000** [comment]
The random pick colour should be always the same. Red and blue

**Comment by anthonyjoeseph** [comment]
magic choice must always have a red background
